services:
  # Simple Microservices
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit-project
    container_name: rabbitmq-mgmt
    ports:
      - "5672:5672"
      - "15672:15672"
  
  amqp:
    build: ./SimpleMicroservices/amqp
    image: kelynwong/amqp
    env_file:
      - ./SimpleMicroservices/amqp/.env
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
  
  log:
    build: ./SimpleMicroservices/log
    image: kelynwong/log
    env_file:
      - ./SimpleMicroservices/log/.env
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
      - amqp

  notification:
    build: ./SimpleMicroservices/notification
    image: kelynwong/notification
    env_file:
      - ./SimpleMicroservices/notification/.env
    ports:
      - "8002:8002"
    depends_on:
      - rabbitmq
      - amqp
      - log

  # Complex Microservices
  group-creation:
    build: ./ComplexMicroservices/GroupCreation
    ports:
      - "8003:8003"
    depends_on:
      - rabbitmq
      - amqp
      - log
      - notification

  enrollment:
    build: ./ComplexMicroservices/enrollment
    ports:
      - "8004:8004"
    depends_on:
      - rabbitmq
      - amqp
      - log
      - notification

  report:
    build: ./ComplexMicroservices/Report
    ports:
      - "8005:8005"
    depends_on:
      - rabbitmq
      - amqp
      - log
      - notification

  task:
    build: ./ComplexMicroservices/Task
    ports:
      - "8006:8006"
    depends_on:
      - rabbitmq
      - amqp
      - log
    
  # Wrapper Microservices
  gemini:
    build: ./ComplexMicroservices/GeminiWrapper
    ports:
      - "8007:8007"
    depends_on:
      - rabbitmq
      - amqp
      - log

  # Frontend
  frontend:
    build: ./Frontend
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - amqp
      - log
      - notification
      - enrollment
      - group-creation
      - report
      - task
      - gemini