services:
  # Simple Microservices
  amqp:
    build: ./SimpleMicroservices/amqp
    ports:
      - "8000:8000"
  
  log:
    build: ./SimpleMicroservices/log
    ports:
      - "8001:8001"
    depends_on:
      - amqp

  notification:
    build: ./SimpleMicroservices/notification
    ports:
      - "8002:8002"
    depends_on:
      - amqp
      - log

  # Complex Microservices
  group-creation:
    build: ./ComplexMicroservices/GroupCreation
    ports:
      - "8003:8003"
    depends_on:
      - amqp
      - log
      - notification

  enrollment:
    build: ./ComplexMicroservices/enrollment
    ports:
      - "8004:8004"
    depends_on:
      - amqp
      - log
      - notification

  report:
    build: ./ComplexMicroservices/Report
    ports:
      - "8005:8005"
    depends_on:
      - amqp
      - log
      - notification

  task:
    build: ./ComplexMicroservices/Task
    ports:
      - "8006:8006"
    depends_on:
      - amqp
      - log
    
  # Wrapper Microservices
  gemini:
    build: ./ComplexMicroservices/GeminiWrapper
    ports:
      - "8007:8007"
    depends_on:
      - amqp
      - log

  # Frontend
  frontend:
    build: ./Frontend
    ports:
      - "8080:8080"
    depends_on:
      - amqp
      - log
      - notification
      - enrollment
      - group-creation
      - report
      - task
      - gemini