services:
  # Simple Microservices
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit-project
    container_name: rabbitmq-mgmt
    ports:
      - "5672:5672"
      - "15672:15672"
  
  amqp:
    build: ./SimpleMicroservices/amqp
    image: kelynwong/amqp
    env_file:
      - ./SimpleMicroservices/amqp/.env
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
  
  log:
    build: ./SimpleMicroservices/log
    image: kelynwong/log
    env_file:
      - ./SimpleMicroservices/log/.env
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
      - amqp
    restart: on-failure

  notification:
    build: ./SimpleMicroservices/notification
    image: kelynwong/notification
    env_file:
      - ./SimpleMicroservices/notification/.env
    ports:
      - "8002:8002"
    depends_on:
      - rabbitmq
      - amqp
      - log
    restart: on-failure

  # Complex Microservices
  idea:
    build: ./ComplexMicroservices/GenerateIdeas
    ports:
      - "5000:5000"
    env_file:
      - ./ComplexMicroservices/GenerateIdeas/.env
    depends_on:
      - rabbitmq
      - amqp
      - log
      - notification
    restart: on-failure

  group-creation:
    build: ./ComplexMicroservices/GroupCreation
    ports:
      - "5001:5000"
    env_file:
    - ./ComplexMicroservices/GroupCreation/.env
    depends_on:
      - rabbitmq
      - amqp
      - log
      - notification
    restart: on-failure

  enrollment:
    build: ./ComplexMicroservices/enrollment
    ports:
      - "5002:5000"
    env_file:
    - ./ComplexMicroservices/enrollment/.env
    depends_on:
      - rabbitmq
      - amqp
      - log
      - notification
    restart: on-failure
  
  # task:
  #   build: ./ComplexMicroservices/Task
  #   ports:
  #     - "5003:5000"
  #   depends_on:
  #     - rabbitmq
  #     - amqp
  #     - log
  #     - notification
  #   restart: on-failure