openapi: 3.0.0
info:
  title: Group Creation Complex Microservice
  description: API for creating groups with complex attributes
  version: 1.0.0
servers:
  - url: http://localhost:5100
paths:
  /groupcreation:
    post:
      summary: Create a new group with subgroups and assign users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                oneOf:
                  - $ref: '#/components/schemas/Group'
                  - $ref: '#/components/schemas/Subgroup'
                  - type: array
                    items:
                      type: integer
      responses:
        '201':
          description: Group creation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupCreationResponse'
components:
  schemas:
    GroupCreationResponse:
      type: object
      properties:
        subgroup_result:
          type: array
          items:
            $ref: '#/components/schemas/Subgroup'
          description: List of created subgroups
        final_group_result:
          $ref: '#/components/schemas/Group'
          description: Updated group details after user assignment
    Group:
      type: object
      properties:
        groupId:
          type: integer
          description: The groupId of the group
        name:
          type: string
          description: The name of the group
        description:
          type: string
          description: A brief description of the group
        picture:
          type: string
          description: An image associated
        size:
          type: integer
          description: Number of people in a group
        createdById:
          type: integer
          description: UserId of user who created group
        createdByUsername:
          type: string
          description: Username of user who created group
        createdDateTime:
          type: string
          description: Date and Time of creation of group
        groupUsers:
          type: array
          description: List of users (objects) who are assigned to group
          items:
            type: object
    Subgroup:
      type: object
      properties:
        subGroupId:
          type: integer
          description: The subGroupId of the subgroup
        groupId:
          type: integer
          description: The groupId of group the subgroup is in
        name:
          type: string
          description: The name of the subgroup
        description:
          type: string
          description: A brief description of the subgroup
        picture:
          type: string
          description: An image associated
        size:
          type: integer
          description: Number of people in a subgroup
        subGroupUsers:
          type: array
          description: List of users (objects) who join the subgroup
          items:
            type: object